GET http://localhost:3000

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "samuelj1323",
    "password": "password1234"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "samuelj1323",
    "password": "password1234"
}
